[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "GreasyPidgin"
version = "0.2"
description = "Algorithmic composition toolkit inspired by slippery chicken"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }  # or whatever you actually use
authors = [
  { name = "Sem Ribeiro Albuquerque Wendt", email = "sem@16161d.net" }
]

dependencies = [
  "numpy",
  "matplotlib",
  "musicscore",
  "mido",
  "python-osc",
]

[project.urls]
Homepage = "https://github.com/sem-16161d/GreasyPidgin"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]